version: '3.1'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana-finances
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus-finances
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/udp"
      - "16686:16686"
      - "14268:14268"
  app-demo:
    container_name: app-demo
    image: app-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      REQUEST_LOG_ENABLED: "true"
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
    ports:
      - "8080:8080"
      - "8001:8001"

volumes:
  prometheus_data: {}
  grafana_data: {}
